Add CK_FUNCTION_LIST_EXTENDED structure
Also fix CK_FUNCTION_LIST field types and C_GetFunctionList definition to
match PKCS#11 interface: PKCS#11 expects pointer to pointer to
CK_FUNCTION_LIST as argument in C_GetFunctionList, but we passed pointer
to this structure.
Change Function to Pointer in CK_FUNCTION_LIST fields as we got an
IllegalArgumentException: "Invalid Structure field, type class
com.sun.jna.Function has unknown native alignment". Function is not a
mapping type for JNA.

Up version to 3.4.0.